import { prisma } from '@/core/libs/prisma';

const ConfigScale = [
  {
    DataID: 'SCL001',
    DataCenter: 'DC001',
    BrandName: 'Toledo',
    ComPort: 'COM1',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 2,
    WeightSize: 8,
    ToledoFormat: true,
    RightToLeftWeight: false,
    Status: 'A',
    HWID: 'BFEBFBFF000406E3',
    DataHash: BigInt('1234567890123456789'),
  },
  {
    DataID: 'SCL002',
    DataCenter: 'DC001',
    BrandName: 'Mettler',
    ComPort: 'COM2',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 2,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'A',
    HWID: 'BFEBFBFF000406E3',
    DataHash: BigInt('2345678901234567890'),
  },
  {
    DataID: 'SCL003',
    DataCenter: 'DC001',
    BrandName: 'Sartorius',
    ComPort: 'COM3',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 2,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'A',
    HWID: 'BFEBFBFF000406E3',
    DataHash: BigInt('3456789012345678901'),
  },
  {
    DataID: 'SCL004',
    DataCenter: 'DC001',
    BrandName: 'Avery',
    ComPort: 'COM4',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 2,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'A',
    HWID: 'BFEBFBFF000406E3',
    DataHash: BigInt('4567890123456789012'),
  },
  {
    DataID: 'SCL005',
    DataCenter: 'DC001',
    BrandName: 'Rice Lake',
    ComPort: 'COM5',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 2,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'A',
    HWID: 'BFEBFBFF000406E3',
    DataHash: BigInt('5678901234567890123'),
  },
];

const Seed_ConfigScale = () =>
  prisma.$transaction(
    ConfigScale.map((row) => {
      const { DataID, ...rest } = row;
      return prisma.configScale.upsert({
        where: { BrandName: row.BrandName },
        update: rest,
        create: row,
      });
    })
  );

export { Seed_ConfigScale };
