import type { ConfigScale } from '@/../prisma-client';
import { prisma } from '@/core/libs/prisma';

const data: ConfigScale[] = [
  {
    DataID: 'AND',
    DataCenter: null,
    BrandName: 'AND',
    ComPort: 'COM1',
    BitPerSecond: 2400,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 18,
    StartAscii: 10,
    EndAscii: 13,
    WeightPos: 8,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Avery',
    DataCenter: null,
    BrandName: 'Avery',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Cardinal',
    DataCenter: null,
    BrandName: 'Cardinal',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Commandor',
    DataCenter: null,
    BrandName: 'Commandor',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Custom',
    DataCenter: null,
    BrandName: 'Custom',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 13,
    WeightPos: 5,
    WeightSize: 6,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'GSE',
    DataCenter: null,
    BrandName: 'GSE',
    ComPort: 'COM1',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 21,
    StartAscii: 1,
    EndAscii: 10,
    WeightPos: 3,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Kubota',
    DataCenter: null,
    BrandName: 'Kubota',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Linear',
    DataCenter: null,
    BrandName: 'Linear',
    ComPort: 'COM1',
    BitPerSecond: 9600,
    DataBit: 8,
    Parity: 'None',
    StopBit: 1,
    PacketSize: 12,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 5,
    WeightSize: 6,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'MT',
    DataCenter: null,
    BrandName: 'MT',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 17,
    StartAscii: 2,
    EndAscii: 13,
    WeightPos: 5,
    WeightSize: 6,
    ToledoFormat: true,
    RightToLeftWeight: false,
    Status: 'Y',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Red Lion',
    DataCenter: null,
    BrandName: 'Red Lion',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Rice Lake',
    DataCenter: null,
    BrandName: 'Rice Lake',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 14,
    StartAscii: 2,
    EndAscii: 10,
    WeightPos: 2,
    WeightSize: 8,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Schenck',
    DataCenter: null,
    BrandName: 'Schenck',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Transmate',
    DataCenter: null,
    BrandName: 'Transmate',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
  {
    DataID: 'Yamato',
    DataCenter: null,
    BrandName: 'Yamato',
    ComPort: 'COM1',
    BitPerSecond: 1200,
    DataBit: 7,
    Parity: 'Even',
    StopBit: 1,
    PacketSize: 0,
    StartAscii: 0,
    EndAscii: 0,
    WeightPos: 0,
    WeightSize: 0,
    ToledoFormat: false,
    RightToLeftWeight: false,
    Status: 'N',
    HWID: null,
    DataHash: null,
  },
];

const Seed_ConfigScale = () =>
  prisma.$transaction(
    data.map((row) => {
      const { BrandName, ...rest } = row;
      return prisma.configScale.upsert({
        where: { BrandName },
        update: rest,
        create: row,
      });
    })
  );

export { Seed_ConfigScale };
