import { z } from 'zod';

// Base schema for Weight
const WeightSchema = z.object({
  DataID: z.string(),
  DataCenter: z.string().nullable(),
  DocID: z.string().nullable(),
  DocNoIn: z.string().nullable(),
  DocNoOut: z.string().nullable(),
  WeightModeDataID: z.string().nullable(),
  CarRegister: z.string().nullable(),
  CarRegister2: z.string().nullable(),
  TruckDataID: z.string().nullable(),
  RFIDTagDataID: z.string().nullable(),
  WeightTypeDataID: z.string().nullable(),
  CustomerDataID: z.string().nullable(),
  ProductDataID: z.string().nullable(),
  TransporterDataID: z.string().nullable(),
  DriverDataID: z.string().nullable(),
  SequenceWeightIn: z.string().nullable(),
  WeightDateIn: z.date().nullable(),
  WeightTimeIn: z.date().nullable(),
  WeightIn: z.number().nullable(),
  UserLogInDataIDIn: z.string().nullable(),
  WeightScaleIDIn: z.string().nullable(),
  TicketPrintCountIn: z.number().nullable(),
  SequenceWeightOut: z.string().nullable(),
  WeightDateOut: z.date().nullable(),
  WeightTimeOut: z.date().nullable(),
  WeightOut: z.number().nullable(),
  UserLogInDataIDOut: z.string().nullable(),
  WeightScaleIDOut: z.string().nullable(),
  TicketPrintCountOut: z.number().nullable(),
  Weight: z.number().nullable(),
  WeightAdjust: z.number().nullable(),
  AdjustPercent: z.number().nullable(),
  AdjustPercentWeight: z.number().nullable(),
  WeightAdjKey1: z.number().nullable(),
  WeightAdjCal1: z.number().nullable(),
  WeightAdjKey2: z.number().nullable(),
  WeightAdjCal2: z.number().nullable(),
  WeightAdjKey3: z.number().nullable(),
  WeightAdjCal3: z.number().nullable(),
  WeightNet: z.number().nullable(),
  Price: z.number().nullable(),
  Tax: z.number().nullable(),
  ProductUnitDataID: z.string().nullable(),
  KgToUnit: z.number().nullable(),
  Amount: z.number().nullable(),
  AmountAdjKey1: z.number().nullable(),
  AmountAdjCal1: z.number().nullable(),
  AmountAdjKey2: z.number().nullable(),
  AmountAdjCal2: z.number().nullable(),
  AmountAdjKey3: z.number().nullable(),
  AmountAdjCal3: z.number().nullable(),
  AmountNet: z.number().nullable(),
  Remark1: z.string().nullable(),
  Remark2: z.string().nullable(),
  Remark3: z.string().nullable(),
  Remark4: z.string().nullable(),
  SequenceRegisterIn: z.string().nullable(),
  RegisterDateIn: z.date().nullable(),
  RegisterTimeIn: z.date().nullable(),
  UserLogInDataIDRegisterIn: z.string().nullable(),
  RegisterStationIDIn: z.string().nullable(),
  SequenceRegisterOut: z.string().nullable(),
  RegisterDateOut: z.date().nullable(),
  RegisterTimeOut: z.date().nullable(),
  UserLogInDataIDRegisterOut: z.string().nullable(),
  RegisterStationIDOut: z.string().nullable(),
  FlagRegisterStatus: z.string({ required_error: 'กรุณาเลือกวิธีลงทะเบียน' }).min(1, 'กรุณาเลือกวิธีลงทะเบียน'),
  FlagAutoSaveIn: z.string().nullable(),
  FlagAutoSaveOut: z.string().nullable(),
  FlagPlatformEdgeSensorIn: z.string().nullable(),
  FlagPlatformEdgeSensorOut: z.string().nullable(),
  FlagStatus: z.string().nullable(),
  FlagComplete: z.string().nullable(),
  FlagPayment: z.string().nullable(),
  PaymentDataID: z.string().nullable(),
  PaymentDate: z.date().nullable(),
  PaymentTime: z.date().nullable(),
  PaymentUserLogInDataID: z.string().nullable(),
  WeightNetStandard: z.number().nullable(),
  WeightNetTolerancePositive: z.number().nullable(),
  WeightNetToleranceNegative: z.number().nullable(),
  WeightNetApproveUserLogInDataID: z.string().nullable(),
  FlagCancel: z.string().nullable(),
  HWID: z.string().nullable(),
  ExtendedData: z.string().nullable(),
  DataHash: z.bigint().nullable(),
  FlagUploadIn: z.string().nullable(),
  FlagUploadOut: z.string().nullable(),
});

// Schema for creating new Weight
export const createWeightSchema = WeightSchema;

// Schema for updating Weight
export const updateWeightSchema = WeightSchema.partial();

// Type inference
export type WeightSchema = z.infer<typeof WeightSchema>;
export type CreateWeightSchema = z.infer<typeof createWeightSchema>;
export type UpdateWeightSchema = z.infer<typeof updateWeightSchema>;
