export const PRISMA_ERROR_MESSAGE = {
  // Database Connection Errors (P1000-P1017)
  P1000: 'Connection to database failed. Please check your connection details and try again',
  P1001: 'Could not connect to the database server. Please ensure the server is running',
  P1002: 'Connection to database timed out. Please try again in a moment',
  P1003: 'Database not found. Please verify the database name and try again',
  P1008: 'Request timed out. Please try again.',
  P1009: 'Database already exists.',
  P1010: 'Access denied. Please check your database permissions.',
  P1011: 'TLS connection failed. Please check your security settings.',
  P1012: 'Invalid schema format. Please check your Prisma schema.',
  P1013: 'Invalid database connection string.',
  P1014: 'Required database table or view is missing.',
  P1015: "Your database version doesn't support some features.",
  P1016: 'Incorrect number of parameters in query.',
  P1017: 'Server connection was lost. Please try again.',

  // Query Engine Errors (P2000-P2037)
  P2000: 'The provided value is too long for this field.',
  P2001: 'We could not find what you were looking for',
  P2002: 'This information already exists in the system',
  P2003: 'The operation failed because of a reference constraint.',
  P2004: 'Database constraint violation occurred.',
  P2005: 'Invalid data type for this field.',
  P2006: 'The provided value is not valid for this field.',
  P2007: 'Data validation failed.',
  P2008: 'Query syntax error.',
  P2009: 'Query validation failed.',
  P2010: 'Raw query execution failed.',
  P2011: 'Please fill in all required fields',
  P2012: 'Some required information is missing',
  P2013: 'Missing required argument for operation.',
  P2014: 'The operation would break a required relationship between records.',
  P2015: 'Related record not found.',
  P2016: 'Query interpretation error.',
  P2017: 'Records are not properly connected in the relation.',
  P2018: 'Required connected records were not found.',
  P2019: 'Input validation error.',
  P2020: 'Value is out of range.',
  P2021: 'Table not found in database.',
  P2022: 'Column not found in database.',
  P2023: 'Inconsistent data found in database.',
  P2024: 'The system is busy right now. Please try again in a moment',
  P2025: 'Could not find the necessary information to complete this action',
  P2026: "The database doesn't support this operation.",
  P2027: 'Multiple database errors occurred.',
  P2028: 'Transaction error occurred.',
  P2029: 'Query parameter limit exceeded.',
  P2030: 'Full-text search index not found.',
  P2031: 'MongoDB must be run as a replica set.',
  P2033: 'Number too large for database field.',
  P2034: 'Another user made changes at the same time. Please try again',
  P2035: 'Database assertion violation occurred.',
  P2036: 'External connector error occurred.',
  P2037: 'Too many database connections opened.',

  // Migration Errors (P3000-P3022)
  P3000: 'Failed to create database.',
  P3001: 'Warning: This migration may result in data loss.',
  P3002: 'Migration failed and was rolled back.',
  P3003: 'Migration format is no longer valid.',
  P3004: 'Cannot modify system database.',
  P3005: 'Cannot run migration on non-empty database.',
  P3006: 'Migration failed in testing environment.',
  P3007: 'Some requested features are not supported for migrations.',
  P3008: 'Migration has already been applied.',
  P3009: 'Failed migrations found. New migrations cannot be applied.',
  P3010: 'Migration name is too long.',
  P3011: 'Cannot roll back - migration was never applied.',
  P3012: 'Cannot roll back - migration is not in failed state.',
  P3013: 'Multiple database providers are no longer supported.',
  P3014: 'Could not create shadow database for testing.',
  P3015: 'Migration file is missing.',
  P3016: 'Database cleanup after failed migration was incomplete.',
  P3017: 'Specified migration not found.',
  P3018: 'Migration failed to apply. Please resolve the error first.',
  P3019: 'Database provider mismatch in configuration.',
  P3020: 'Shadow database creation is disabled.',
  P3021: 'Foreign keys cannot be created on this database.',
  P3022: 'Direct database schema modifications are disabled.',

  // Introspection Errors (P4000-P4002)
  P4000: 'Database schema analysis failed.',
  P4001: 'The database is empty.',
  P4002: 'Database schema is inconsistent.',

  // Prisma Accelerate Errors (P6000-P6010)
  P6000: 'An unexpected error occurred.',
  P6001: 'Invalid database connection URL.',
  P6002: 'Invalid API key.',
  P6003: 'System is experiencing high traffic. Please try again later',
  P6004: 'This request is taking longer than expected. Please try again',
  P6005: 'Invalid parameters provided.',
  P6006: 'This Prisma version is not supported.',
  P6008: 'Failed to start database connection.',
  P6009: 'Response size limit exceeded.',
  P6010: 'Your Accelerate project is disabled.',

  // Prisma Pulse Errors (P6100-P6105)
  P6100: 'Service temporarily unavailable. Please try again later.',
  P6101: 'Database connection error.',
  P6102: 'Authentication failed.',
  P6103: 'Prisma Pulse is not enabled.',
  P6104: 'Account access restricted.',
  P6105: 'Incompatible Prisma version.',
} as const;
